// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvL1JSkIVkS3Rj8GvvztpW9ywgV8ZI648',
    appId: '1:949602912599:web:6e2e03a3765d15e6179612',
    messagingSenderId: '949602912599',
    projectId: 'soso-bfd63',
    authDomain: 'soso-bfd63.firebaseapp.com',
    storageBucket: 'soso-bfd63.appspot.com',
    measurementId: 'G-6NJNTTTWNE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnn-m_3_cjVVgnbzaN0aPyUKvHbHUW_hg',
    appId: '1:949602912599:android:c45710448adf8e1b179612',
    messagingSenderId: '949602912599',
    projectId: 'soso-bfd63',
    storageBucket: 'soso-bfd63.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0jbuhGWirrIwzqk4cOKGCYM8w7Imkr9I',
    appId: '1:949602912599:ios:70ec90fce2940e84179612',
    messagingSenderId: '949602912599',
    projectId: 'soso-bfd63',
    storageBucket: 'soso-bfd63.appspot.com',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0jbuhGWirrIwzqk4cOKGCYM8w7Imkr9I',
    appId: '1:949602912599:ios:70ec90fce2940e84179612',
    messagingSenderId: '949602912599',
    projectId: 'soso-bfd63',
    storageBucket: 'soso-bfd63.appspot.com',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvL1JSkIVkS3Rj8GvvztpW9ywgV8ZI648',
    appId: '1:949602912599:web:08f12426cfc4103e179612',
    messagingSenderId: '949602912599',
    projectId: 'soso-bfd63',
    authDomain: 'soso-bfd63.firebaseapp.com',
    storageBucket: 'soso-bfd63.appspot.com',
    measurementId: 'G-6HF0QMLZDC',
  );

}